---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    attributes:
      common:
        auth:
          group:
            managed:
              kibana: true
    run_list:
      - recipe[chef_common_auth::default]
